### ISSUE TITLE
Remove this repository

### ISSUE THREAD

**Issue by zware** [python/speed.python.org#1]
This repo is out of date, speed.python.org is now serving https://github.com/zware/codespeed.  That repo should probably be moved from my personal account to replace this one, as well (I'm not sure what it takes to do that).

**Comment by ewdurbin** [comment]
@zware I can make you a collaborator on this repo. at that point you'd be welcome to forcepush/replace all of the existing commits.

**Comment by zware** [comment]
That would work, thanks!

**Comment by ewdurbin** [comment]
@zware i've created a new @python/codespeed team for the python org. you're now a maintainer for that team and thus an admin on this repository.
